name: Build and Push Docker Images

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "v[0-9]+.[0-9]+.[0-9]*"

  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [fsdownload, websocketrust]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get branch or tag name
        id: branch-tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/master ]]; then
            echo "name=latest" >> $GITHUB_OUTPUT
          else
            echo "name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.app }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fl-${{ matrix.app }}:${{ steps.branch-tag.outputs.name }}
